import{S as y,A as x}from"./assets/vendor-BNdPdaeU.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function c(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=c(e);fetch(e.href,t)}})();const i={THEME_KEY:"theme",themeToggler:document.querySelector("#theme-switcher")};function f(){return JSON.parse(localStorage.getItem(i.THEME_KEY))||!1}function d(r){localStorage.setItem(i.THEME_KEY,JSON.stringify(r))}function h(){f()&&(i.themeToggler.checked=!0,document.querySelector("body").classList.add("dark"))}function b(r){r.target.checked?(document.body.classList.add("dark"),d(!0)):(d(!1),document.body.classList.remove("dark"))}//! to main
const g={scrollBtn:document.querySelector(".scroll-up--btn")};function v(){window.pageYOffset>300?g.scrollBtn.classList.add("show-btn"):g.scrollBtn.classList.remove("show-btn")}function w(r,s){let c;return function(...o){clearTimeout(c),c=setTimeout(()=>r.apply(this,o),s)}}function S(){window.scrollTo({top:0,behavior:"smooth"})}const L=w(v,300);//!To main
const E="/gitpub-team-project/assets/sprite-B7CrHXRV.svg",j=[{src1x:"my-projects/rectangle-11-1x.jpg",src2x:"my-projects/rectangle-11-2x.jpg",src:"my-projects/rectangle-11-1x.jpg",alt:"Wallet webservice "},{src1x:"my-projects/rectangle-9-1x.jpg",src2x:"my-projects/rectangle-9-2x.jpg",src:"my-projects/rectangle-9-1x.jpg",alt:"Green harvest webservice"},{src1x:"my-projects/rectangle-12-1x.jpg",src2x:"my-projects/rectangle-12-2x.jpg",src:"my-projects/rectangle-12-1x.jpg",alt:"English Exellence website"},{src1x:"my-projects/rectangle-10-1x.jpg",src2x:"my-projects/rectangle-10-2x.jpg",src:"my-projects/rectangle-10-1x.jpg",alt:"power pulse webservice"},{src1x:"my-projects/rectangle-7-1x.jpg",src2x:"my-projects/rectangle-7-2x.jpg",src:"my-projects/rectangle-7-1x.jpg",alt:"mimino website"},{src1x:"my-projects/rectangle-8-1x.jpg",src2x:"my-projects/rectangle-8-2x.jpg",src:"my-projects/rectangle-8-1x.jpg",alt:"vyshyvanka vibes Landing Page"},{src1x:"my-projects/rectangle-6-1x.jpg",src2x:"my-projects/rectangle-6-2x.jpg",src:"my-projects/rectangle-6-1x.jpg",alt:"chego jewelry website"},{src1x:"my-projects/rectangle-4-1x.jpg",src2x:"my-projects/rectangle-4-2x.jpg",src:"my-projects/rectangle-4-1x.jpg",alt:"energy flow webservice"},{src1x:"my-projects/rectangle-5-1x.jpg",src2x:"my-projects/rectangle-5-2x.jpg",src:"my-projects/rectangle-5-1x.jpg",alt:"fruitbox online store"},{src1x:"my-projects/first-screen-1-1x.jpg",src2x:"my-projects/first-screen-1-2x.jpg",src:"my-projects/first-screen-1-1x.jpg",alt:"starlight studio landing page"}],p="/gitpub-team-project/",m=document.querySelector(".gallery"),l=document.querySelector(".btn-load-more-my-project");let T=new y(".gallery a",{captionsData:"alt",captionDelay:250}),a=0;const O=3;function $(r){const s=r.map(({src1x:c,src2x:o,src:e,alt:t,h3:n})=>`
      <li>
  <a href="${e}" class="gallery-link">
    <img class="image-my-project" srcset="${p}${c} 1x, ${p}${o} 2x" src="${p}${e}" alt="${t}" />
  </a>
  <div class="div-my-project">
    <p class="text-my-project">React, JavaScript, Node JS, Git</p>
    <h3 class="names-my-project">${t}</h3>
    <button class="button-my-project" onclick="window.open('https://github.com/Marakasss/gitpub-team-project', '_blank')">
      <span class="visit-my-project">VISIT</span>
      <svg class="svg-my-project" height="14.5" width="14.5">
        <use class="svg-visit-my-project" href="${E}#icon-visit-arrow"></use>
      </svg>
    </button>
  </div>
</li>
    `).join("");m.insertAdjacentHTML("beforeend",s),T.refresh()}async function u(r=!0){l.disabled=!0,l.classList.add("disabled");const s=j.slice(a,a+O),c=m.lastElementChild;await new Promise(e=>setTimeout(e,200)),$(s);const o=c?c.nextElementSibling:m.firstElementChild;r&&o&&o.scrollIntoView({behavior:"smooth",block:"start"}),a+=s.length,a>=j.length?l.style.display="none":(l.disabled=!1,l.classList.remove("disabled"))}l.addEventListener("click",u);x.init();h();i.themeToggler.addEventListener("change",b);window.addEventListener("scroll",L);g.scrollBtn.addEventListener("click",S);u(!1);
//# sourceMappingURL=index.js.map
