import{S as k,i as v,a as E,b as T,A as B}from"./assets/vendor-BDt1dWUS.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))o(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const u of n.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&o(u)}).observe(document,{childList:!0,subtree:!0});function t(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function o(r){if(r.ep)return;r.ep=!0;const n=t(r);fetch(r.href,n)}})();const j=document.querySelector(".header--open-menu"),d=document.querySelector(".menu"),w=document.querySelector(".close-btn"),I=document.querySelectorAll(".menu-list > li");function $(){!j||!d||!w||(j.addEventListener("click",L),w.addEventListener("click",g),I.forEach(e=>{e.addEventListener("click",g)}),window.innerWidth<=768&&q(d))}function L(){d.classList.add("open"),document.body.classList.add("menu-open")}function g(){d.classList.remove("open"),document.body.classList.remove("menu-open")}function q(e){let s=null,t=null;document.addEventListener("touchstart",o=>{e.classList.contains("open")||(s=o.changedTouches[0].screenX)},!1),document.addEventListener("touchend",o=>{if(e.classList.contains("open")||(t=o.changedTouches[0].screenX,s===null||t===null))return;s-t>50&&L(),s=null,t=null},!1),e.addEventListener("touchstart",o=>{e.classList.contains("open")&&(s=o.changedTouches[0].screenX)},!1),e.addEventListener("touchend",o=>{if(!e.classList.contains("open")||(t=o.changedTouches[0].screenX,s===null||t===null))return;s-t<-50&&g(),s=null,t=null},!1)}const p={THEME_KEY:"theme",themeToggler:document.querySelector("#theme-switcher")};function M(){return JSON.parse(localStorage.getItem(p.THEME_KEY))||!1}function b(e){localStorage.setItem(p.THEME_KEY,JSON.stringify(e))}function P(){M()&&(p.themeToggler.checked=!0,document.querySelector("body").classList.add("dark"))}function O(e){e.target.checked?(document.body.classList.add("dark"),b(!0)):(b(!1),document.body.classList.remove("dark"))}//! to main
const h={scrollBtn:document.querySelector(".scroll-up--btn")};function D(){window.pageYOffset>300?h.scrollBtn.classList.add("show-btn"):h.scrollBtn.classList.remove("show-btn")}function R(e,s){let t;return function(...o){clearTimeout(t),t=setTimeout(()=>e.apply(this,o),s)}}function N(){window.scrollTo({top:0,behavior:"smooth"})}const A=R(D,300);//!To main
const C="/gitpub-team-project/assets/sprite-oahpSgbj.svg",x=[{src1x:"my-projects/rectangle-11-1x.jpg",src2x:"my-projects/rectangle-11-2x.jpg",src:"my-projects/rectangle-11-1x.jpg",alt:"Wallet webservice "},{src1x:"my-projects/rectangle-9-1x.jpg",src2x:"my-projects/rectangle-9-2x.jpg",src:"my-projects/rectangle-9-1x.jpg",alt:"Green harvest webservice"},{src1x:"my-projects/rectangle-12-1x.jpg",src2x:"my-projects/rectangle-12-2x.jpg",src:"my-projects/rectangle-12-1x.jpg",alt:"English Exellence website"},{src1x:"my-projects/rectangle-10-1x.jpg",src2x:"my-projects/rectangle-10-2x.jpg",src:"my-projects/rectangle-10-1x.jpg",alt:"power pulse webservice"},{src1x:"my-projects/rectangle-7-1x.jpg",src2x:"my-projects/rectangle-7-2x.jpg",src:"my-projects/rectangle-7-1x.jpg",alt:"mimino website"},{src1x:"my-projects/rectangle-8-1x.jpg",src2x:"my-projects/rectangle-8-2x.jpg",src:"my-projects/rectangle-8-1x.jpg",alt:"vyshyvanka vibes Landing Page"},{src1x:"my-projects/rectangle-6-1x.jpg",src2x:"my-projects/rectangle-6-2x.jpg",src:"my-projects/rectangle-6-1x.jpg",alt:"chego jewelry website"},{src1x:"my-projects/rectangle-4-1x.jpg",src2x:"my-projects/rectangle-4-2x.jpg",src:"my-projects/rectangle-4-1x.jpg",alt:"energy flow webservice"},{src1x:"my-projects/rectangle-5-1x.jpg",src2x:"my-projects/rectangle-5-2x.jpg",src:"my-projects/rectangle-5-1x.jpg",alt:"fruitbox online store"},{src1x:"my-projects/first-screen-1-1x.jpg",src2x:"my-projects/first-screen-1-2x.jpg",src:"my-projects/first-screen-1-1x.jpg",alt:"starlight studio landing page"}],m="/gitpub-team-project/",f=document.querySelector(".gallery"),c=document.querySelector(".btn-load-more-my-project");let F=new k(".gallery a",{captionsData:"alt",captionDelay:250}),i=0;const X=3;function H(e){const s=e.map(({src1x:t,src2x:o,src:r,alt:n})=>`
      <li>
  <a href="${r}" class="gallery-link">
    <img data-aos="flip-up" data-aos-duration="500" data-aos-easing="linear"
    class="image-my-project" srcset="${m}${t} 1x, ${m}${o} 2x" src="${m}${r}" alt="${n}" />
  </a>
    <p class="text-my-project">React, JavaScript, Node JS, Git</p>
      <div class="div-my-project" 
      data-aos="fade-up" 
      data-aos-anchor-placement="bottom-bottom"
      data-aos-easing="linear"
      data-aos-duration="500">
    <h3 class="names-my-project">${n}</h3>
    <button class="button-my-project" onclick="window.open('https://github.com/Marakasss/gitpub-team-project', '_blank')">
      <span class="visit-my-project">VISIT</span>
      <svg class="svg-my-project" height="24" width="24">
        <use class="svg-visit-my-project" href="${C}#icon-visit-arrow"></use>
      </svg>
    </button>
  </div>
</li>
    `).join("");f.insertAdjacentHTML("beforeend",s),F.refresh()}async function S(e=!0){c.disabled=!0,c.classList.add("disabled");const s=x.slice(i,i+X),t=f.lastElementChild;await new Promise(r=>setTimeout(r,200)),H(s);const o=t?t.nextElementSibling:f.firstElementChild;e&&o&&o.scrollIntoView({behavior:"smooth",block:"start"}),i+=s.length,i>=x.length?c.style.display="none":(c.disabled=!1,c.classList.remove("disabled"))}c.addEventListener("click",S);const l=document.getElementById("work-together-form");let a={email:"",comment:""};const V=()=>{const e=document.getElementById("work-together-modal-close-button"),s=document.getElementById("work-together-modal");e.addEventListener("click",y),s.addEventListener("click",function(t){document.getElementById("work-together-modal-content").contains(t.target)||y()}),l.addEventListener("submit",t=>{if(t.preventDefault(),a.email=l.elements.email.value.trim(),a.comment=l.elements.comment.value.trim(),!a.email||!a.comment){v.error({message:"Please fill out all required fields",backgroundColor:"#EF4040",close:!0,position:"topRight"});return}_(a)})},_=async e=>{const s="https://portfolio-js.b.goit.study/api/requests";try{const t=await E.post(s,e);J(t.data.title,t.data.message),console.log(t),l.reset()}catch(t){v.error({message:`${t}`,backgroundColor:"#EF4040",close:!0,position:"topRight"})}},J=(e,s)=>{document.body.classList.add("no-scroll"),document.getElementById("work-together-modal").classList.add("is-open"),document.getElementById("work-together-modal-caption").innerText=`${e}`,document.getElementById("work-together-modal-paragraph").innerText=`${s}`,document.addEventListener("keyup",function(t){t.key==="Escape"&&y()})};function y(){document.getElementById("work-together-modal").classList.remove("is-open"),document.body.classList.remove("no-scroll")}const K=document.querySelector(".swiper-wrapper"),U=document.querySelector(".reviews-not-found");async function W(){try{return(await E.get("https://portfolio-js.b.goit.study/api/reviews")).data}catch{v.error({title:"Error",message:"Failed to load reviews"}),U.hidden=!1}}function Y(e){K.innerHTML=e.map(({review:s,author:t,avatar_url:o})=>`
      <li class="swiper-slide">
        <div class="review-card">
          <p class="review-text">${s}</p>
          <div class="review-author">
            <img src="${o}" alt="${t}" class="review-author-avatar" />
            <span class="review-author-name">${t}</span>
          </div>
        </div>
      </li>
    `).join(""),G()}function G(){new T(".swiper",{navigation:{nextEl:".reviews-button-next",prevEl:".reviews-button-prev"},keyboard:{enabled:!0,onlyInViewport:!0},slidesPerView:1,spaceBetween:20,breakpoints:{1280:{slidesPerView:2,spaceBetween:32}},grabCursor:!0,on:{reachEnd(e){e.navigation.nextEl.classList.add("reviews-button-disabled")},reachBeginning(e){e.navigation.prevEl.classList.add("reviews-button-disabled")},fromEdge(e){e.navigation.nextEl.classList.remove("reviews-button-disabled"),e.navigation.prevEl.classList.remove("reviews-button-disabled")}}})}W().then(Y);B.init();P();p.themeToggler.addEventListener("change",O);window.addEventListener("scroll",A);h.scrollBtn.addEventListener("click",N);S(!1);V();$();
//# sourceMappingURL=index.js.map
