import{S as j}from"./assets/vendor-CgTBfC_f.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const i={THEME_KEY:"theme",themeToggler:document.querySelector("#theme-switcher")};function y(){return JSON.parse(localStorage.getItem(i.THEME_KEY))||!1}function p(r){localStorage.setItem(i.THEME_KEY,JSON.stringify(r))}function u(){y()&&(i.themeToggler.checked=!0,document.querySelector("body").classList.add("dark"))}function x(r){r.target.checked?(document.body.classList.add("dark"),p(!0)):(p(!1),document.body.classList.remove("dark"))}//! to main
const m=[{src1x:"/my-projects/rectangle-11-1x.jpg",src2x:"/my-projects/rectangle-11-2x.jpg",src:"/my-projects/rectangle-11-1x.jpg",alt:"Wallet webservice "},{src1x:"/my-projects/rectangle-9-1x.jpg",src2x:"/my-projects/rectangle-9-2x.jpg",src:"/my-projects/rectangle-9-1x.jpg",alt:"Green harvest webservice"},{src1x:"/my-projects/rectangle-12-1x.jpg",src2x:"/my-projects/rectangle-12-2x.jpg",src:"/my-projects/rectangle-12-1x.jpg",alt:"English Exellence website"},{src1x:"/my-projects/rectangle-10-1x.jpg",src2x:"/my-projects/rectangle-10-2x.jpg",src:"/my-projects/rectangle-10-1x.jpg",alt:"power pulse webservice"},{src1x:"/my-projects/rectangle-7-1x.jpg",src2x:"/my-projects/rectangle-7-2x.jpg",src:"/my-projects/rectangle-7-1x.jpg",alt:"mimino website"},{src1x:"/my-projects/rectangle-8-1x.jpg",src2x:"/my-projects/rectangle-8-2x.jpg",src:"/my-projects/rectangle-8-1x.jpg",alt:"vyshyvanka vibes Landing Page"},{src1x:"/my-projects/rectangle-6-1x.jpg",src2x:"/my-projects/rectangle-6-2x.jpg",src:"/my-projects/rectangle-6-1x.jpg",alt:"chego jewelry website"},{src1x:"/my-projects/rectangle-4-1x.jpg",src2x:"/my-projects/rectangle-4-2x.jpg",src:"/my-projects/rectangle-4-1x.jpg",alt:"energy flow webservice"},{src1x:"/my-projects/rectangle-5-1x.jpg",src2x:"/my-projects/rectangle-5-2x.jpg",src:"/my-projects/rectangle-5-1x.jpg",alt:"fruitbox online store"},{src1x:"/my-projects/first-screen-1-1x.jpg",src2x:"/my-projects/first-screen-1-2x.jpg",src:"/my-projects/first-screen-1-1x.jpg",alt:"starlight studio landing page"}],g=document.querySelector(".gallery"),l=document.querySelector(".btn-load-more-my-project");let f=new j(".gallery a",{captionsData:"alt",captionDelay:250}),a=0;const h=3;function b(r){const s=r.map(({src1x:o,src2x:c,src:e,alt:t,h3:n})=>`
      <li>
  <a href="${e}" class="gallery-link">
    <img class="image-my-project" srcset="${o} 1x, ${c} 2x" src="${e}" alt="${t}" />
  </a>
  <div class="div-my-project">
    <p class="text-my-project">React, JavaScript, Node JS, Git</p>
    <h3 class="names-my-project">${t}</h3>
    <button class="button-my-project" onclick="window.open('https://github.com/Marakasss/gitpub-team-project', '_blank')">
      <span class="visit-my-project">VISIT</span>
      <svg class="svg-my-project" height="14.5" width="14.5">
        <use class="svg-visit-my-project" href="/img/sprite.svg#icon-visit-arrow"></use>
      </svg>
    </button>
  </div>
</li>
    `).join("");g.insertAdjacentHTML("beforeend",s),f.refresh()}async function d(r=!0){l.disabled=!0,l.classList.add("disabled");const s=m.slice(a,a+h),o=g.lastElementChild;await new Promise(e=>setTimeout(e,200)),b(s);const c=o?o.nextElementSibling:g.firstElementChild;r&&c&&c.scrollIntoView({behavior:"smooth",block:"start"}),a+=s.length,a>=m.length?l.style.display="none":(l.disabled=!1,l.classList.remove("disabled"))}l.addEventListener("click",d);u();i.themeToggler.addEventListener("change",x);d(!1);
//# sourceMappingURL=index.js.map
